version: "3.8"
services:
  webserver:
    ports:
      - 80:80
    restart: always
    image: nginx:1.25.3-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/src
  db:
    ports:
      - 5432:5432
    hostname: 'db'
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_DATABASE: user_message_db
      POSTGRES_USER: raptor
      POSTGRES_PASSWORD: lama22
      POSTGRES_ROOT_PASSWORD: lama22
        - .:/docker-entrypoint-initdb.d
          - dbdata:/var/lib/postgresql/data
    depends_on:
      - webserver

  app:
    hostname: 'app'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/xdebug.env
    volumes:
      - ./src:/var/www/src
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
      - webserver

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/src
    depends_on:
      - app

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]


volumes:
  dbdata:
    driver: local